# Generated by Django 6.0.3 on 2026-03-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_specialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='offer_advantages',
            field=models.JSONField(blank=True, default=list, help_text='List of advantages/bullets'),
        ),
        migrations.AddField(
            model_name='form',
            name='offer_button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='offer_button_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='form',
            name='offer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='form',
            name='offer_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
