# Generated by Django 6.0.3 on 2026-03-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_is_specialized_form_offer_advantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='funnel_config',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata for multi-screen specialized funnels'),
        ),
    ]
