# Generated by Django 6.0.3 on 2026-04-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_funnel_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('text', 'Texte court'), ('textarea', 'Texte long'), ('email', 'Email'), ('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple'), ('date', 'Date'), ('number', 'Nombre'), ('file', 'Fichier')], max_length=50),
        ),
    ]
