# Generated by Django 6.0.3 on 2026-04-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formfield_placeholder_alter_formfield_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='step_impressions',
            field=models.JSONField(blank=True, default=dict, help_text='Impressions per step ID: {step_id: count}'),
        ),
        migrations.AddField(
            model_name='form',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
